apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullName" . }}-deployment
  namespace: {{ include "app.fullName" . }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-deployment
    helm.sh/chart: {{ include "chart.fullName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: {{ include "app.fullName" . }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ include "app.fullName" . }}
    spec:
      containers:
        - name: {{ include "app.fullName" . }}-container
          image: "{{ .Values.image.repositoryWithRegistry }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.exposedPort }}
          {{- if .Values.environment }}
          env:
          {{- range $name, $value := .Values.environment}}
            - name: {{ $name | quote}}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.hasSecrets }}
          envFrom:
          - secretRef:
              name: {{ include "app.fullName" . }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe }}
              port: {{ .Values.exposedPort }}
            initialDelaySeconds: 20
            timeoutSeconds: 5
          {{- end }}
          {{- if .Values.startupProbe }}
          startupProbe:
            httpGet:
              path: {{ .Values.startupProbe }}
              port: {{ .Values.exposedPort }}
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 20
          {{- end }}
