apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: db-rest
  namespace: app-releases
spec:
  chart:
    spec:
      chart: simple-app
      sourceRef:
        kind: HelmRepository
        name: charts
        namespace: flux-system
      version: '^2.0.0'
  interval: 5m
  values:
    image:
      updateTagAutomatically: false
      repositoryWithRegistry: "docker.io/derhuerst/db-rest"
      tag: "5"
    exposedPort: 3000
    environment:
      PORT: 3000
    hosts:
      - 'v5.db.juliustens.eu'

# resources:
#   limits:
#     cpu: 200m
#     memory: 256Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

    replicas: 3

    livenessProbe: false
    startupProbe: false
