apiVersion: v1
kind: Secret
metadata:
    name: logzio-otel-metrics-secret
    namespace: logzio-otel-metrics
type: Opaque
data:
    token: ENC[AES256_GCM,data:Jx+Sc9vU7bNXRQF681LLEDizHlYkha38NPJ4+Pu7pzKJhYPk5gMrQXrEaJE=,iv:DkAnpalNvgPIq9a0L2FbB/Br9m68gWah9VTHKQud4iE=,tag:bdaSRC68x2w+a7W7WnHtCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-25T20:25:40Z"
    mac: ENC[AES256_GCM,data:RGOSN/SGzw4/aucyWft2leC+nkkZwU2y1UBk2LCjSEd7DLf2imTmfoV0BFLXMcl+bsCmsRghT2fEv+FWt3NA94K2Av8x70JL7yDichsqIBDLTtnqWFGhOJzOdtFktlabPXM8tpfLsIbD2wV8QY2LzbBeJqJ9nyukceTZ/O4+dMk=,iv:H+sJ69jaZ9AM7htcbvALkmhYgCxWxqSjspun9hQIhCk=,tag:TP0yvKbdypebCvncYJLewg==,type:str]
    pgp:
        - created_at: "2021-10-09T13:51:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxER4EixexCHAQ/7BMzP3KJnfG+mUq8g4yMA+6yYhLudDP2WbWbk3720jCH0
            nVSs2G6qnI12b/BYe6Hd6nYZ2MlziqBwUS4uikJFr7a0kIBK3M/u19wTAR5VnVho
            DhoO959chkOjNYx3FGhrTv+Vzp6KTgB9401iXE9k2jcrlIxtR7Gz747WrVaLQFDb
            5yRgZixrVqu8ejrebjNbQMjmSojzxyyh/IbUO4bKeo4uWdvyhSZfIbD8DhwmXHRB
            kWzIJgIjmVQa22sagadYwY+HMpm2pf50XL7essA9oWHi9zmXVaAJi1wPsF0Uftf3
            UxBGQVXeI9BaNjXnH34KvC/UNoMNtw/vJiXboAyCA6TArNWzxV/IWv/C9KKH7x2F
            aOOz9ntO8qpn0cj4jYfbEoCGKft2KI5vCuimVwmToDoY5zPKinHYMhAZ5fjjg35S
            YtwxteSQ7FGZrwLjWc2Z46nVQ3L5IxPAms2yBZk73j1XK4bhS6IxI3SKRb58Jtaj
            Z6X0MciKxwQK2Wl/8bf7laFQCc1pWNKmoKDjMDzHuWyu1EcwcvkTrDrB+azUzKqV
            Qq0H8Z98mZ6RuwvRbI43sf+tdh1eqs9Xe44slfvBrs3KXSil/AyfiOpmDPjccDKJ
            3nHV5wW7dhP02Ux3P/zY+o+m/+yEdhJmisZGPB2QQ7psYLdl2D2ApzAK0BKthanS
            XgGldDLk/axS1snvnZd0xwioSDzmC7uI6OIE2+5v+jqx4doPXgECBdjrEpmBrq2b
            LhQPqC3hUoO9Uw7NHHzahX0w2qG9BeSh1BzB4zNeFoO4RIeZOMpcGeVkWFnapJY=
            =8ZQC
            -----END PGP MESSAGE-----
          fp: 269A9ADE0A611CD74CB8BC4434C257FCF9AB9265
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
