apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: umami
  namespace: app-releases
spec:
  chart:
    spec:
      chart: simple-app
      sourceRef:
        kind: HelmRepository
        name: charts
        namespace: flux-system
      version: '^2.0.0'
  interval: 5m
  values:
    hasSecrets: true
    image:
      updateTagAutomatically: false
      repositoryWithRegistry: "ghcr.io/umami-software/umami"
      tag: "postgresql-v1.36.1"
    exposedPort: 3000
    environment:
      EXAMPLE: test
    hosts:
      - 'developer.public-transport.earth'
      - 'developer.bahn.guru'

# resources:
#   limits:
#     cpu: 200m
#     memory: 256Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

    livenessProbe: false
    startupProbe: false
