apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: european-transport-feeds
  namespace: app-releases
spec:
  chart:
    spec:
      chart: simple-app
      sourceRef:
        kind: HelmRepository
        name: charts
        namespace: flux-system
      version: '^2.0.0'
  interval: 5m
  values:
    image:
      repositoryWithRegistry: "ghcr.io/public-transport/european-transport-feeds" # {"$imagepolicy": "flux-system:european-transport-feeds-image-policy:name"}
      tag: "v1_802d5a9_2022-06-21T18.35.57Z" # {"$imagepolicy": "flux-system:european-transport-feeds-image-policy:tag"}
    exposedPort: 3000
    environment:
      PORT: 3000
    hosts:
    - 'eu.data.public-transport.earth'

# resources:
#   limits:
#     cpu: 200m
#     memory: 256Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi
# livenessProbe: '/'
# startupProbe: '/'
