apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logzio-otel-metrics
  namespace: logzio-otel-metrics
spec:
  chart:
    spec:
      chart: logzio-otel-k8s-metrics
      sourceRef:
        kind: HelmRepository
        name: logzio
        namespace: flux-system
      version: '^0.0.1'
  values:
    secrets:
      p8s_logzio_name: 'prod'
      ListenerHost: 'https://listener-nl.logz.io:8053'
  valuesFrom:
    - kind: Secret
      name: logzio-otel-metrics-secret
      valuesKey: token
      targetPath: secrets.MetricsToken
  interval: 5m
