apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: public-transport-data-scraper-legacy-proxy
  namespace: app-releases
spec:
  chart:
    spec:
      chart: simple-app
      sourceRef:
        kind: HelmRepository
        name: charts
        namespace: flux-system
      version: '^2.0.0'
  interval: 5m
  values:
    image:
      repositoryWithRegistry: "ghcr.io/juliuste/public-transport-data-scraper-legacy-proxy" # {"$imagepolicy": "flux-system:public-transport-data-scraper-legacy-proxy-image-policy:name"}
      tag: "v1_e1339a1_2022-07-16t16.22.01z" # {"$imagepolicy": "flux-system:public-transport-data-scraper-legacy-proxy-image-policy:tag"}
    exposedPort: 3000
    environment:
      PORT: 3000
    hosts:
      - 'proxy-test.data.public-transport.earth'

# resources:
#   limits:
#     cpu: 200m
#     memory: 256Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

    livenessProbe: false
    startupProbe: false
