# certain namespaces are used in multiple "modules", so they need to be created
# separately before everything else all other namespaces should be created
# directly by the components that need them
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
  - fluent-bit.yaml
  - logzio-otel-metrics.yaml
  - app-releases.yaml
