hasSecrets: false

image:
  repositoryWithRegistry: "docker.io/example/image"
  tag: "latest"
  updateTagAutomatically: true
  tagUpdatePattern: '^v1_[a-fA-F0-9]{7}_(?P<datetime>.*)Z$'
  tagUpdateExtract: '$datetime'

exposedPort: 3000
environment: {}

hosts:
  - some.example.domain

replicas: 2
resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 100Mi
livenessProbe: '/'
startupProbe: '/'
