hasSecrets: false

image:
  repositoryWithRegistry: "docker.io/example/image"
  tag: "latest"
  tagUpdatePattern: '^v1_[a-fA-F0-9]{7}_(?P<datetime>.*)Z$'
  tagUpdateExtract: '$datetime'

exposedPort: 3000
environment: {}

hosts:
  - some.example.domain

replicas: 1
resources:
  limits:
    cpu: 80m
    memory: 128Mi
  requests:
    cpu: 40m
    memory: 64Mi
livenessProbe: '/'
readinessProbe: '/'
